// DB ドキュメント(docs/database/)の台帳。テーブルの日本語名・説明・業務の領域と、項目の共通の説明を定義する。
// テーブルを追加したら、ここにも1行追加する(追加しないと generate-db-docs のテストが失敗する)。

/** 業務の領域。file は docs/database/ に出力するファイル名 */
export const DOMAINS = [
  { key: "system", file: "system.md", title: "システム管理", description: "ユーザー・部署・ロール・権限と、メール送信・帳票の設定" },
  { key: "workflow", file: "workflow.md", title: "承認ワークフロー", description: "承認フロー・承認権限・承認申請と、その履歴" },
  { key: "master", file: "master.md", title: "業務マスタ", description: "取引先・商品・単位・勘定科目・倉庫・ロケーションなどのマスタ" },
  { key: "sales", file: "sales.md", title: "販売", description: "見積・受注・売上・請求・入金" },
  { key: "purchase", file: "purchase.md", title: "購買", description: "購買申請・発注・仕入・支払" },
  { key: "inventory", file: "inventory.md", title: "在庫", description: "在庫・入出庫・入出荷指示・棚卸・品質区分の変更・廃棄・返品・引当" },
  { key: "accounting", file: "accounting.md", title: "会計(仕訳)", description: "仕訳ルール・仕訳の起票イベントと、仕訳データ(DB_JOURNAL)" },
  { key: "progress", file: "progress.md", title: "進捗管理", description: "進捗確認の工程の担当と、完了/進行中の手動設定" },
  { key: "deals", file: "deals.md", title: "商談", description: "商談・面談者・タスク・見込み客の担当者(DB_DEALS)" },
  { key: "other", file: "logs-otp-ui.md", title: "ログ・OTP・画面表示", description: "監査ログ・メール送信ログ(DB_LOG)、OTP(DB_OTP)、お知らせ・画面説明・表示設定(DB_UI)" },
];

/** テーブルの台帳: テーブル名 → { domain, label, description } */
export const TABLES = {
  // ---- システム管理
  users: { domain: "system", label: "ユーザー", description: "システムにログインするユーザー。従業員番号・メールアドレスでログインする" },
  departments: { domain: "system", label: "部署", description: "組織の部署。上位の部署と有効期間を持てる" },
  roles: { domain: "system", label: "ロール", description: "権限をまとめる役割(例: 営業担当、経理)。ユーザーに部署ごとに割り当てる" },
  user_login_states: { domain: "system", label: "ログインの状態", description: "ユーザーごとの、続けてログインに失敗した回数・一時的なロックの期限・ログインを無効にする時刻(ログアウト・無効化・パスワード変更)" },
  user_roles: { domain: "system", label: "ユーザーの所属", description: "ユーザー × 部署 × ロールの割り当て。1人が複数の部署・ロールを持てる" },
  permissions: { domain: "system", label: "権限", description: "画面(resource)と操作(一覧・登録・更新・削除など)の組み合わせ" },
  role_permissions: { domain: "system", label: "ロールの権限", description: "ロールに与える権限の一覧" },
  mail_template_settings: { domain: "system", label: "メール送信・帳票の設定", description: "帳票の種類ごとのメールの件名・本文・宛先(CC/BCC)、帳票テンプレート、ファイル名" },

  // ---- 承認ワークフロー
  approval_authorities: { domain: "workflow", label: "承認権限", description: "申請の種類ごとに、承認できるロールと金額の上限" },
  approval_flows: { domain: "workflow", label: "承認フロー", description: "申請の種類・金額の範囲・条件ごとの承認経路" },
  approval_flow_steps: { domain: "workflow", label: "承認フローの段", description: "承認フローの各段(何段目を、どのロール・ユーザーが承認するか)" },
  workflow_logs: { domain: "workflow", label: "承認の履歴", description: "申請・承認・差戻し・取下げなどの操作の記録" },
  master_approval_requests: { domain: "workflow", label: "承認申請", description: "マスタ・伝票の承認申請。対象の種類(target_type)と対象ID、申請内容のスナップショット、現在の段を持つ" },
  master_approval_contexts: { domain: "workflow", label: "承認申請の審査情報", description: "承認申請に付ける審査用の情報(契約の種類・期間、反社会的勢力のチェック、図面・仕様の備考など)" },

  // ---- 業務マスタ
  units: { domain: "master", label: "単位", description: "個・箱・kg などの単位" },
  unit_conversions: { domain: "master", label: "単位の換算", description: "単位どうしの換算率(例: 1箱 = 12個)" },
  partners: { domain: "master", label: "取引先", description: "得意先・仕入先・見込み客。与信限度額・締め日・支払条件・反社チェックなどを持つ" },
  partner_attachments: { domain: "master", label: "取引先の添付ファイル", description: "取引先に添付した契約書などのファイル(実体は R2)" },
  partner_bank_accounts: { domain: "master", label: "取引先の振込先口座", description: "支払の振込先口座(全銀形式の振込ファイルの作成に使う)。1取引先が複数口座を持てる" },
  partner_contacts: { domain: "master", label: "取引先担当者", description: "取引先の担当者と連絡先。帳票のメール送信先にもなる" },
  partner_contact_document_types: { domain: "master", label: "取引先担当者の送付帳票", description: "取引先担当者ごとに、メールで送る帳票の種類" },
  partner_delivery_destinations: { domain: "master", label: "取引先の納品先", description: "取引先ごとの納品先(受注の納品先の選択に使う)" },
  accounts: { domain: "master", label: "勘定科目", description: "仕訳・購買で使う勘定科目" },
  projects: { domain: "master", label: "プロジェクト", description: "購買申請・発注で使うプロジェクト" },
  tax_categories: { domain: "master", label: "消費税区分", description: "消費税の区分と税率(10%・8%・非課税など)" },
  items: { domain: "master", label: "商品(品目)", description: "販売・購買・在庫で扱う商品。仕入品・販売品・サービスの区分、基本単位、バーコードなどを持つ" },
  item_attachments: { domain: "master", label: "商品の添付ファイル", description: "商品に添付した図面・写真などのファイル(実体は R2)" },
  item_structures: { domain: "master", label: "商品構成", description: "親商品を構成する子商品と数量(部品表)" },
  item_prices: { domain: "master", label: "商品単価", description: "商品の販売単価・仕入単価。取引先・数量・有効期間ごとに設定できる" },
  item_reorder_settings: { domain: "master", label: "発注点", description: "商品 × 倉庫ごとの発注点・安全在庫(欠品の自動提案に使う)" },
  warehouses: { domain: "master", label: "倉庫", description: "自社倉庫・外部倉庫。住所・営業時間などを持つ" },
  warehouse_attachments: { domain: "master", label: "倉庫の添付ファイル", description: "倉庫に添付したファイル(実体は R2)" },
  warehouse_available_days: { domain: "master", label: "倉庫の稼働日", description: "倉庫の曜日ごとの稼働可否と時間帯" },
  warehouse_contacts: { domain: "master", label: "倉庫担当者", description: "外部倉庫の担当者と連絡先(出荷指示書・入荷指示書の送付先)" },
  warehouse_contact_document_types: { domain: "master", label: "倉庫担当者の送付帳票", description: "倉庫担当者ごとに、メールで送る帳票の種類(出荷指示書・入荷指示書)" },
  business_locations: { domain: "master", label: "営業拠点", description: "自社の営業拠点(発注の納品場所などに使う)" },
  locations: { domain: "master", label: "ロケーション", description: "倉庫内の保管場所(棚など)" },

  // ---- 販売
  quotes: { domain: "sales", label: "見積", description: "見積のヘッダー(得意先・件名・有効期限・合計金額・承認状態など)。版(バージョン)を管理する" },
  quote_items: { domain: "sales", label: "見積明細", description: "見積の明細(商品・数量・単価・金額・税区分)" },
  quote_attachments: { domain: "sales", label: "見積の添付ファイル", description: "見積書 PDF・添付ファイル(実体は R2)" },
  quote_history_logs: { domain: "sales", label: "見積の変更履歴", description: "見積の変更内容の記録" },
  sales_orders: { domain: "sales", label: "受注", description: "受注のヘッダー(得意先・受注日・納品先・合計金額・承認状態など)" },
  sales_order_items: { domain: "sales", label: "受注明細", description: "受注の明細(商品・数量・単価・金額)" },
  sales_order_item_reservations: { domain: "sales", label: "受注明細の引当実績", description: "受注明細 × 倉庫の在庫の引当・出荷の記録(追跡用)" },
  sales_order_attachments: { domain: "sales", label: "受注の添付ファイル", description: "注文請書 PDF・添付ファイル(実体は R2)" },
  sales_order_history_logs: { domain: "sales", label: "受注の変更履歴", description: "受注の変更内容の記録" },
  sales_invoices: { domain: "sales", label: "売上", description: "売上のヘッダー(得意先・売上日・合計金額・承認状態・請求の状態など)" },
  sales_invoice_items: { domain: "sales", label: "売上明細", description: "売上の明細(商品・数量・単価・金額)" },
  sales_invoice_attachments: { domain: "sales", label: "売上の添付ファイル", description: "売上関連書類 PDF・添付ファイル(実体は R2)" },
  sales_invoice_history_logs: { domain: "sales", label: "売上の変更履歴", description: "売上の変更内容の記録" },
  billing_headers: { domain: "sales", label: "請求", description: "得意先への請求のヘッダー(締め期間・請求日・支払期限・請求金額・消込の状態)" },
  billing_items: { domain: "sales", label: "請求明細", description: "請求に含める売上の一覧" },
  payment_receipts: { domain: "sales", label: "入金(請求の消込)", description: "請求に対する入金の記録(手動の消込)" },
  cash_receipts: { domain: "sales", label: "入金(単体)", description: "請求を介さない入金(前受金など)" },
  cash_receipt_advance_applications: { domain: "sales", label: "前受金の充当", description: "単体入金の前受金を、売上に充当した記録" },

  // ---- 購買
  purchase_requests: { domain: "purchase", label: "購買申請", description: "購買申請のヘッダー(申請者・勘定科目・プロジェクト・承認状態など)" },
  purchase_request_items: { domain: "purchase", label: "購買申請明細", description: "購買申請の明細(品目・数量・見積単価・希望納期)" },
  purchase_request_attachments: { domain: "purchase", label: "購買申請の添付ファイル", description: "購買申請の参考資料(見積書 PDF など、実体は R2)" },
  orders: { domain: "purchase", label: "発注", description: "発注のヘッダー(仕入先・発注日・納品場所・合計金額・承認状態・前払の有無など)" },
  order_items: { domain: "purchase", label: "発注明細", description: "発注の明細(商品・数量・単価・金額)" },
  order_attachments: { domain: "purchase", label: "発注の添付ファイル", description: "発注書 PDF・添付ファイル(実体は R2、版を管理)" },
  purchase_recognitions: { domain: "purchase", label: "仕入", description: "仕入(購買計上)のヘッダー(仕入先・計上日・合計金額・承認状態・支払の状態)" },
  purchase_recognition_items: { domain: "purchase", label: "仕入明細", description: "仕入の明細(商品・数量・単価・金額)" },
  purchase_recognition_attachments: { domain: "purchase", label: "仕入の添付ファイル", description: "仕入計上書 PDF・添付ファイル(実体は R2)" },
  purchase_recognition_history_logs: { domain: "purchase", label: "仕入の変更履歴", description: "仕入の変更内容の記録" },
  purchase_recognition_receipts: { domain: "purchase", label: "仕入と検収の紐づけ", description: "仕入と検収記録(入庫)の対応。同じ納品への二重支払を警告するために使う" },
  payment_headers: { domain: "purchase", label: "支払", description: "仕入先への支払のヘッダー(支払日・支払金額・消込の状態)" },
  payment_header_items: { domain: "purchase", label: "支払明細", description: "支払に含める仕入・検収記録の一覧" },
  payment_disbursements: { domain: "purchase", label: "支払実績(支払の消込)", description: "支払に対する実際の支払の記録(手動の消込)" },

  // ---- 在庫
  stocks: { domain: "inventory", label: "在庫", description: "商品 × 倉庫 × ロケーション × ロット × 品質区分ごとの在庫数" },
  stock_transactions: { domain: "inventory", label: "在庫の増減履歴", description: "入庫・出庫・棚卸・品質区分の変更・廃棄・返品による在庫の増減の記録" },
  item_stock_reservations: { domain: "inventory", label: "在庫の引当(商品単位)", description: "受注による商品単位の在庫の引当(以前の方式。倉庫別の引当より前に承認された受注用)" },
  warehouse_stock_reservations: { domain: "inventory", label: "在庫の引当(倉庫単位)", description: "受注による商品 × 倉庫単位の在庫の引当数" },
  item_receipt_headers: { domain: "inventory", label: "入庫", description: "入庫(検収)のヘッダー。仕入先・移動元倉庫・入庫日・承認状態・発注との紐づけなど" },
  item_receipt_items: { domain: "inventory", label: "入庫明細", description: "入庫の明細(商品・倉庫・ロケーション・ロット・数量・検品結果)" },
  item_receipt_attachments: { domain: "inventory", label: "入庫の添付ファイル", description: "検収書 PDF(実体は R2、版を管理)" },
  item_receipt_instructions: { domain: "inventory", label: "入荷指示", description: "外部倉庫への入荷指示のヘッダー" },
  item_receipt_instruction_items: { domain: "inventory", label: "入荷指示明細", description: "入荷指示の明細と、入庫による消込の状況" },
  receipt_instruction_attachments: { domain: "inventory", label: "入荷指示書", description: "入荷指示書 PDF(実体は R2)" },
  item_shipment_headers: { domain: "inventory", label: "出庫", description: "出庫のヘッダー。得意先・移動先倉庫・出庫日・承認状態・受注との紐づけ・納品書など" },
  item_shipment_items: { domain: "inventory", label: "出庫明細", description: "出庫の明細(商品・倉庫・ロケーション・ロット・品質区分・数量)" },
  item_shipment_instructions: { domain: "inventory", label: "出荷指示", description: "外部倉庫への出荷指示のヘッダー" },
  item_shipment_instruction_items: { domain: "inventory", label: "出荷指示明細", description: "出荷指示の明細と、出庫による消込の状況" },
  shipment_instruction_attachments: { domain: "inventory", label: "出荷指示書", description: "出荷指示書 PDF(実体は R2)" },
  stock_audits: { domain: "inventory", label: "棚卸", description: "棚卸(実在庫との差の調整)。1行 = 1回の棚卸" },
  stock_reclassifications: { domain: "inventory", label: "品質区分の変更", description: "良品・破損品・検品待ちの区分の変更。1行 = 1回の変更" },
  stock_disposals: { domain: "inventory", label: "廃棄", description: "在庫の廃棄。1行 = 1回の廃棄" },
  stock_returns: { domain: "inventory", label: "返品", description: "仕入先への返品・得意先からの返品。1行 = 1回の返品" },

  // ---- 会計(仕訳)
  journal_posting_rules: { domain: "accounting", label: "仕訳ルール", description: "会計事象(売上・仕入・入金・支払・前受・前払)ごとの借方・貸方の勘定科目" },
  journal_posting_patterns: { domain: "accounting", label: "仕訳パターン", description: "仕訳の組(会計事象×伝票区分×本体・消費税・充当)ごとの借方・貸方の勘定科目。無い組は仕訳ルールの科目から組み立てる" },
  journal_posting_events: { domain: "accounting", label: "仕訳の起票イベント", description: "仕訳を作るべき伝票の一覧(送信待ち)。仕訳本体は DB_JOURNAL に作る" },
  journal_entries: { domain: "accounting", label: "仕訳(旧)", description: "以前の1行型の仕訳テーブル。現在は使っていない" },
  journal_batches: { domain: "accounting", label: "仕訳バッチ", description: "1つの会計事象 = 1バッチ。借方と貸方の合計が一致する単位(DB_JOURNAL)" },
  journal_lines: { domain: "accounting", label: "仕訳明細", description: "仕訳バッチの借方・貸方の各行(DB_JOURNAL)" },

  // ---- 進捗管理
  progress_stage_owners: { domain: "progress", label: "工程の既定の担当", description: "進捗確認の工程ごとの既定の担当者" },
  progress_case_assignments: { domain: "progress", label: "案件の工程の担当", description: "案件 × 工程ごとの担当者(既定の担当を上書きする)" },
  progress_case_stage_overrides: { domain: "progress", label: "案件の工程の完了設定", description: "案件 × 工程ごとの完了/進行中の手動設定" },
  document_completion_overrides: { domain: "progress", label: "伝票の完了設定", description: "伝票ごとの完了/進行中の手動設定。進捗確認の工程の状態に反映する" },

  // ---- 商談(DB_DEALS)
  deals: { domain: "deals", label: "商談", description: "見込み客・得意先との商談(日時・場所・内容・状態・担当者)" },
  deal_attendees: { domain: "deals", label: "面談者", description: "商談で会った相手。氏名などはその時点の内容で保存する" },
  deal_tasks: { domain: "deals", label: "商談のタスク", description: "次回までに行うタスクと担当・期限・完了" },
  deal_attachments: { domain: "deals", label: "商談の添付ファイル", description: "商談の添付ファイル(実体は R2)" },
  deal_quotes: { domain: "deals", label: "商談と見積の紐づけ", description: "商談に関連する見積(見積は業務DBにあるため外部キーは無い)" },
  prospect_contacts: { domain: "deals", label: "見込み客の担当者", description: "商談の入力中にその場で登録する、見込み客の担当者" },

  // ---- ログ・OTP・画面表示
  audit_logs: { domain: "other", label: "監査ログ", description: "登録・更新・削除などの操作の記録(変更前後の値を含む)(DB_LOG)" },
  mail_delivery_logs: { domain: "other", label: "メール送信ログ・送信待ち", description: "メール・Slack の送信待ちと送信結果。Cron が1分ごとに送信する(DB_LOG)" },
  otp_challenges: { domain: "other", label: "OTP", description: "取引先向けダウンロードの確認コードと、有効期限・試行回数(DB_OTP)" },
  announcements: { domain: "other", label: "お知らせ", description: "ダッシュボードの「システムからのお知らせ」(DB_UI)" },
  screen_descriptions: { domain: "other", label: "画面説明", description: "画面ごとに見出しの下に表示する説明文(DB_UI)" },
  user_preferences: { domain: "other", label: "ユーザーの表示設定", description: "ユーザーごとの色・ダークモードの設定(DB_UI)" },
};

/** 特定のテーブルの項目の説明(「テーブル名.項目名」)。共通の辞書・ソースのコメントより優先する */
export const COLUMN_OVERRIDES = {
  "deals.start_time": "開始時刻(HH:MM)",
  "deals.end_time": "終了時刻(HH:MM)",
  "partner_bank_accounts.branch_code": "支店コード(3桁)",
  "journal_posting_events.requested_by_id": "起票した人(従業員番号)",
  "journal_batches.posted_by_id": "仕訳にした人(従業員番号。別 DB のため外部キーは無い)",
  "orders.paid_at": "支払済みにした日時(前払)",
  "sales_orders.prepaid_at": "入金済みにした日時(前受)",
};

/**
 * 項目の共通の説明(スキーマのソースにコメントが無い場合に使う)。テーブルに依らず同じ意味の項目名のみ。
 * 外部キーの項目は、生成時に「参照先」列に参照先のテーブルが表示される。
 */
export const COLUMN_DICTIONARY = {
  id: "ID(主キー)",
  code: "コード",
  surrogate_id: "内部ID(コードを変更しても変わらない識別子)",
  name: "名称",
  title: "件名・タイトル",
  description: "説明",
  memo: "備考",
  comment: "コメント",
  status: "状態",
  type: "種別",
  kind: "種類",
  category: "分類",
  version: "版(バージョン)",
  revision: "改訂番号",
  sort_order: "表示順",
  position: "表示順・位置",
  is_active: "有効かどうか",
  is_default: "既定かどうか",
  created_at: "作成日時",
  created_by: "作成者(従業員番号)",
  updated_at: "更新日時",
  updated_by: "更新者(従業員番号)",
  // 承認
  current_approval_layer: "承認中の段(何段目の承認待ちか)",
  approval_flow_id: "使用中の承認フロー",
  request_id: "承認申請",
  request_type: "申請の種類",
  target_type: "承認の対象の種類",
  target_id: "承認の対象のID",
  snapshot_data: "申請時点の内容(JSON)",
  action: "操作(申請・承認・差戻しなど)",
  layer: "段",
  flow_id: "承認フロー",
  step_order: "段の順番",
  step_name: "段の名前",
  approver_id: "承認者(ユーザー)",
  approver_role_id: "承認者のロール",
  min_amount: "金額の下限",
  max_amount: "金額の上限",
  match_field: "フローを選ぶ条件の項目名",
  match_value: "フローを選ぶ条件の値",
  requested_at: "申請日時",
  // 取引先・連絡先
  partner_id: "取引先",
  partner_name: "取引先名",
  supplier_id: "仕入先",
  contact_id: "担当者(参照先のテーブルの担当者)",
  contact_type: "連絡先の種別",
  email: "メールアドレス",
  phone: "電話番号",
  phone_number: "電話番号",
  fax: "FAX番号",
  fax_number: "FAX番号",
  postal_code: "郵便番号",
  address: "住所",
  department_name: "部署名",
  is_email_target: "メール送信の対象かどうか",
  document_type: "帳票の種類",
  credit_limit: "与信限度額",
  closing_day: "締め日",
  payment_month_offset: "支払月(締め日から何か月後か)",
  payment_day: "支払日",
  payment_method: "支払方法",
  payment_terms: "支払条件",
  corporate_number: "法人番号",
  contract_type: "契約の種類",
  contract_date: "契約日",
  contract_valid_from: "契約の開始日",
  contract_valid_to: "契約の終了日",
  contract_memo: "契約の備考",
  anti_social_check_status: "反社会的勢力のチェック状況",
  anti_social_check_memo: "反社会的勢力のチェックの備考",
  bank_name: "銀行名",
  branch_name: "支店名",
  account_number: "口座番号",
  internal_user_id: "自社側の担当ユーザー",
  // ユーザー・組織
  user_id: "ユーザー",
  employee_number: "従業員番号",
  password_hash: "パスワードのハッシュ値",
  role_id: "ロール",
  project_id: "プロジェクト",
  applicant_id: "申請者(従業員番号)",
  permission_id: "権限",
  resource: "画面(権限の単位)",
  department_surrogate_id: "部署(内部ID)",
  parent_department_surrogate_id: "上位の部署(内部ID)",
  target_department_surrogate_id: "対象の部署(内部ID)",
  applicant_department_surrogate_id: "申請部署(申請者が複数の部署に所属する場合に選んだ部署、内部ID)",
  input_person_employee_number: "入力担当者(従業員番号)",
  sales_person_employee_number: "営業担当者(従業員番号)",
  purchase_person_employee_number: "購買担当者(従業員番号)",
  assignee_employee_number: "担当者(従業員番号)",
  // 自社情報(帳票の印字用)
  company_name: "自社名(帳票の印字用)",
  company_department: "自社の部署名(帳票の印字用)",
  company_address: "自社の住所(帳票の印字用)",
  company_tel: "自社の電話番号(帳票の印字用)",
  company_fax: "自社のFAX番号(帳票の印字用)",
  // 商品・単位
  item_id: "商品",
  item_name: "品名(マスタに無い品目も入力できる)",
  unit_code: "単位",
  base_unit_code: "基本単位",
  from_unit_code: "換算元の単位",
  to_unit_code: "換算先の単位",
  conversion_factor: "換算率",
  tax_type: "税の扱い(税込・税抜など)",
  tax_category_code: "消費税区分",
  tax_rate: "税率",
  is_purchased: "仕入品かどうか",
  is_sales: "販売品かどうか",
  is_service: "サービス(在庫を持たない)かどうか",
  product_barcode: "商品のバーコード",
  original_purchased_item_id: "元の仕入品",
  supplier_part_number: "仕入先の品番",
  parent_item_id: "親商品",
  child_item_id: "子商品(構成部品)",
  quantity_required: "必要数量",
  price_type: "単価の種類(販売・仕入)",
  min_quantity: "適用する最小数量",
  valid_from: "有効期間の開始日",
  valid_to: "有効期間の終了日",
  cost_price: "原価",
  drawing_number: "図面番号",
  specification_memo: "仕様の備考",
  general_memo: "一般の備考",
  // 倉庫・在庫
  warehouse_id: "倉庫",
  location_id: "ロケーション",
  lot_number: "ロット番号",
  quality_status: "品質区分(良品・破損品・検品待ち)",
  from_quality_status: "変更前の品質区分",
  to_quality_status: "変更後の品質区分",
  quantity: "数量",
  reserved_quantity: "引当数量",
  instructed_quantity: "指示数量",
  received_quantity: "入庫数量",
  shipped_quantity: "出庫数量",
  reorder_point: "発注点",
  safety_stock: "安全在庫",
  storage_type: "ファイルの保存方法(R2・外部URL)",
  storage_restrictions: "保管上の制約",
  business_start_time: "営業開始時刻",
  business_end_time: "営業終了時刻",
  available_day_of_week: "曜日",
  time_slot_memo: "時間帯の備考",
  inspection_status: "検品結果",
  inspection_memo: "検品の備考",
  performed_at: "実施日時",
  return_reason: "返品の理由",
  return_date: "返品日",
  received_date: "入庫日",
  shipped_date: "出庫日",
  instructed_ship_date: "出荷予定日",
  instructed_receive_date: "入荷予定日",
  instruction_id: "指示",
  instruction_header_id: "指示のヘッダー",
  receipt_header_id: "入庫のヘッダー",
  receipt_item_id: "入庫明細",
  shipment_header_id: "出庫のヘッダー",
  item_receipt_id: "入庫(検収記録)",
  delivery_warehouse_id: "納品先の倉庫",
  ref_id: "関連する伝票のID",
  // 伝票(共通)
  quote_id: "見積",
  source_quote_id: "元の見積",
  sales_order_id: "受注",
  sales_order_item_id: "受注明細",
  sales_invoice_id: "売上",
  order_id: "発注",
  order_item_id: "発注明細",
  purchase_request_item_id: "購買申請明細",
  purchase_recognition_id: "仕入",
  billing_header_id: "請求",
  payment_header_id: "支払",
  cash_receipt_id: "単体入金",
  deal_id: "商談",
  order_type: "発注の種類",
  order_date: "発注日・受注日",
  quote_date: "見積日",
  valid_until: "有効期限",
  invoice_date: "売上日",
  recognition_date: "仕入計上日",
  billing_date: "請求日",
  payment_date: "支払予定日",
  paid_date: "支払日",
  receipt_date: "入金日",
  due_date: "期限",
  delivery_date: "納期",
  delivery_place: "納品場所",
  terms: "取引条件",
  period_start: "対象期間の開始日",
  period_end: "対象期間の終了日",
  unit_price: "単価",
  estimated_unit_price: "見積単価",
  amount: "金額",
  tax_amount: "消費税額",
  total_amount: "合計金額",
  total_credit_amount: "貸方の合計金額",
  input_type: "入力方法(マスタから選択・手入力)",
  is_prepaid: "前受・前払かどうか",
  is_paid: "支払済み(前払)かどうか",
  supplier_invoice_number: "仕入先の請求書番号",
  reconciliation_status: "消込の状態",
  reconciled_by_id: "消込をした人",
  reconciled_at: "消込日時",
  applied_by_id: "充当をした人",
  applied_at: "充当日時",
  invoice_pdf_r2_path: "請求書 PDF の保存先(R2)",
  instruction_document_r2_path: "指示書 PDF の保存先(R2)",
  actual_product_photo_r2_path: "現物写真の保存先(R2)",
  item_attachment_r2_path: "添付ファイルの保存先(R2)",
  // 添付ファイル
  file_name: "ファイル名",
  file_type: "ファイルの種類(MIMEタイプ)",
  attachment_r2_path: "ファイルの保存先(R2 のキー)",
  external_url: "外部URL(R2 ではなく外部に置く場合)",
  uploaded_at: "登録日時",
  uploaded_by_id: "登録した人",
  qr_code_key: "QRコード用のキー",
  // 変更履歴
  changed_at: "変更日時",
  changed_by_id: "変更した人",
  // 仕訳
  account_code: "勘定科目",
  account_name: "勘定科目名",
  debit_account_code: "借方の勘定科目",
  debit_amount: "借方の金額",
  credit_account_code: "貸方の勘定科目",
  credit_amount: "貸方の金額",
  entry_date: "計上日",
  event_type: "会計事象の種類",
  external_mapping_code: "会計ソフト側のコード",
  batch_id: "仕訳バッチ",
  project_name: "プロジェクト名",
  source_ref_id: "元の伝票のID",
  posted_at: "仕訳にした日時",
  error_message: "エラーの内容",
  // 進捗・完了設定
  stage_key: "工程(進捗確認の工程キー)",
  root_kind: "案件の起点となる伝票の種類",
  root_id: "案件の起点となる伝票のID",
  assignee_type: "担当の種類(ユーザー・部署・ロール)",
  assignee_ref: "担当(ユーザー・部署・ロールのID)",
  forced_state: "手動で設定した状態(完了・進行中)",
  document_id: "伝票のID",
  // メール・通知
  smtp_from: "送信元のメールアドレス",
  cc_address: "CC のメールアドレス",
  bcc_address: "BCC のメールアドレス",
  subject_template: "件名のひな形",
  body_template: "本文のひな形",
  report_template_path: "帳票テンプレートの保存先(R2)",
  report_layout_path: "帳票テンプレートを変換したレイアウトの保存先(R2)",
  report_layout_status: "帳票テンプレートの変換の状態",
  report_layout_error: "帳票テンプレートの変換のエラー",
  recipient_to: "宛先(To)",
  recipient_cc: "宛先(CC)",
  subject: "件名",
  body: "本文",
  attached_r2_path: "添付ファイルの保存先(R2)",
  retry_count: "再送の回数",
  next_attempt_at: "次に送信を試す日時",
  // 監査ログ・OTP
  table_name: "対象のテーブル",
  record_id: "対象のレコードのID",
  old_values: "変更前の値(JSON)",
  new_values: "変更後の値(JSON)",
  performed_by_id: "操作した人",
  expires_at: "有効期限",
  attempt_count: "試行回数",
  // 商談・タスク
  location: "場所",
  is_done: "完了したかどうか",
  done_at: "完了日時",
  linked_at: "紐づけた日時",
  linked_by: "紐づけた人",
  // お知らせ
  is_important: "重要なお知らせかどうか",
  is_published: "公開中かどうか",
  start_date: "開始日",
  end_date: "終了日",
};
